# Generated by Django 4.2.17 on 2026-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thucdon',
            name='hinh_anh',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hình ảnh (URL)'),
        ),
    ]
